services:

  search:
    image: bluespice/search:${VERSION}
    volumes:
      - ${DATADIR}/search/data:/usr/share/opensearch/data
    healthcheck:
      test: curl -f http://localhost:9200
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  database:
    image: mariadb:10.5
    volumes:
      - ${DATADIR}/database/data:/var/lib/mysql
      - ${DATADIR}/database/logs:/var/log/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASS}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MARIADB_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  wiki-web:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy
  wiki-task:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy
