services:

  search:
    image: bluespice/search:${VERSION}
    volumes:
      - ${DATADIR}/search:/usr/share/opensearch/data
    healthcheck:
      test: curl -f http://localhost:9200
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  database:
    image: bluespice/database:${VERSION}
    volumes:
      - ${DATADIR}/database/data:/var/lib/mysql
      - ${DATADIR}/database/logs:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    healthcheck:
      test: mysqladmin ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  wiki-web:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy
  wiki-task:
    depends_on:
        database:
            condition: service_healthy
        search:
            condition: service_healthy
  antivirus:
    image: clamav/clamav:stable
    volumes:
      - ${DATADIR}/antivirus:/var/lib/clamav
    profiles:
      - av